# Generated by Django 4.1.1 on 2022-09-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('ano', models.CharField(max_length=255)),
                ('qtd_donos', models.CharField(max_length=255)),
                ('preco', models.IntegerField(default=1000)),
            ],
        ),
    ]
